from flask import Flask, render_template, request

app = Flask(__name__)

# Diccionario de traducción de nombres
traduccion_nombres = {
"Adrián": "Adrian",
"Álvaro": "Alvaro",
"Andrés": "Andrew",
"Ángel": "Angel",
"Belén": "Beth",
"Blanca": "Bianca",
"César": "Caesar",
"Claudia": "Claudia",
"Damián": "Damian",
"Diego": "Diego",
"Dolores": "Dolores",
"Eduardo": "Edward",
"Elisa": "Elise",
"Emilio": "Emil",
"Esperanza": "Hope",
"Felipe": "Philip",
"Fernando": "Ferdinand",
"Gabriel": "Gabriel",
"Graciela": "Graciela",
"Inés": "Ines",
"Ignacio": "Ignatius",
"Irene": "Irene",
"Javier": "Javier",
"Juanita": "Juanita",
"Julio": "Julius",
"Leonor": "Eleanor",
"Lorenzo": "Lawrence",
"Lucía": "Lucy",
"Manuel": "Manuel",
"Margarita": "Margaret",
"Mercedes": "Mercedes",
"Miguel Ángel": "Michael Angel",
"Miriam": "Miriam",
"Natalia": "Natalia",
"Octavio": "Octavius",
"Olivia": "Olivia",
"Patricia": "Patricia",
"Raquel": "Rachel",
"Ricardo": "Richard",
"Rodrigo": "Rodrigo",
"Román": "Roman",
"Rosario": "Rosario",
"Santiago": "James",
"Sebastián": "Sebastian",
"Sofía": "Sophia",
"Teresa": "Teresa",
"Víctor": "Victor",
"Violeta": "Violet",
"Xavier": "Xavier",
"Yolanda": "Yolanda",
"Alejandro": "Alexander",
"Ana": "Anna",
"Antonio": "Anthony",
"Beatriz": "Beatrice",
"Carlos": "Charles",
"Carmen": "Carmen",
"Cristina": "Christine",
"David": "David",
"Elena": "Helen",
"Enrique": "Henry",
"Esteban": "Stephen",
"Francisco": "Francis",
"Gabriela": "Gabrielle",
"Gonzalo": "Gonzalo",
"Isabel": "Isabella",
"Javier": "Xavier",
"Jorge": "George",
"José": "Joseph",
"Juan": "John",
"Laura": "Laura",
"Luis": "Louis",
"Manuel": "Manuel",
"María": "Mary",
"Marta": "Martha",
"Miguel": "Michael",
"Natalia": "Natalie",
"Pablo": "Paul",
"Patricia": "Patricia",
"Pedro": "Peter",
"Raúl": "Ralph",
"Ricardo": "Richard",
"Roberto": "Robert",
"Rodrigo": "Rodrigo",
"Rosa": "Rose",
"Salvador": "Salvador",
"Samuel": "Samuel",
"Sergio": "Sergio",
"Silvia": "Sylvia",
"Susana": "Susan",
"Teresa": "Theresa",
"Tomás": "Thomas",
"Valentina": "Valentina",
"Victoria": "Victoria",
"Víctor": "Victor",
"Virginia": "Virginia",
"Xavier": "Xavier",
"Yolanda": "Yolanda",
"Zacarías": "Zacharias",
"Zara": "Zara",
"Zoila": "Zoila",
"Aurora": "Aurora",
"Arturo": "Arthur",
"Mónica": "Monica",
"Bernardo": "Bernard",
"Ingrid": "Ingrid",
"Joaquín": "Joaquin",
"Sandra": "Sandra",
"Aurelio": "Aurelio",
"Leonor": "Leonora",
"Alberto": "Albert",
"Roxana": "Roxanne",
"Raimundo": "Raymond",
"Gabriela": "Gabrielle",
"Leonel": "Lionel",
"Daniela": "Danielle",
"Feliciano": "Feliciano",
"Marcelina": "Marceline",
"Gonzalo": "Gonzalo",
"Rosalía": "Rosalie",
"Hipólito": "Hippolytus",
"Celestina": "Celestine",
"Dámaso": "Damaso",
"Renata": "Renata",
"Lorenzo": "Lorenzo",
"Ariadna": "Ariadne",
"Eulalia": "Eulalia",
"Gilberto": "Gilbert",
"Constanza": "Constance",
"Norberto": "Norbert",
"Emilia": "Emilia",
"Fernán": "Fernan",
"Marcelo": "Marcelo",
"Leticia": "Leticia",
"Evaristo": "Evaristo",
"Berenice": "Berenice",
"Aníbal": "Hannibal",
"Milagros": "Miracles",
"Felipe": "Philip",
"Graciela": "Graciela",
"Arturo": "Arthur",
"Elvira": "Elvira",
"Modesto": "Modesto",
"Rocío": "Rocio",
"Cándido": "Candido",
"Priscila": "Priscilla",
"Fidel": "Fidel",
"Griselda": "Griselda",
"Valerio": "Valerio",
"Marina": "Marina",
"Marcos": "Mark",
"Ezequiel": "Ezekiel",
"Elsa": "Elsa",
"Bruno": "Bruno",
"Alicia": "Alice",
"Rodolfo": "Rudolph",
"Carolina": "Caroline",
"Ulises": "Ulysses",
"Beatriz": "Beatrice",
"Feliciano": "Feliciano",
"Mariana": "Mariana",
"Apolo": "Apollo",
"Leonora": "Leonora",
"Iñaki": "Iñaki",
"Gisela": "Giselle",
"Aldo": "Aldo",
"Bárbara": "Barbara",
"Leopoldo": "Leopold",
"Cristina": "Christina",
"Evaristo": "Evaristo",
"Susana": "Susan",
"Rogelio": "Roger",
"Zaira": "Zara",
"Clemente": "Clement",
"Isabella": "Isabella",
"Maximiliano": "Maximilian",
"Rebeca": "Rebecca",
"Hugo": "Hugo",
"Celestina": "Celestina",
"Liliana": "Liliana",
"Tobías": "Tobias",
"Paloma": "Paloma",
"Agustín": "Augustine",
"Ángela": "Angela",
"Amadeo": "Amadeus",
"Tatiana": "Tatiana",
"Gervasio": "Gervasio",
"Elena": "Helen",
"Maximiliano": "Maximilian",
"Oriana": "Oriana",
"Adelmo": "Adelmo",
"Margot": "Margot",
"Félix": "Felix",
"Ximena": "Ximena",
"Luciano": "Lucian",
"Carmela": "Carmela",
"Humberto": "Humberto",
"Renata": "Renata",
"Simón": "Simon",
"Estela": "Estella",
"Mauricio": "Maurice"

}





@app.route('/', methods=['GET', 'POST'])
def traducir_nombre():
    nombre_ingles = None

    if request.method == 'POST':
        nombre_espanol = request.form['nombre_espanol'].capitalize()  # Convierte la primera letra a mayúscula
        nombre_ingles = traduccion_nombres.get(nombre_espanol, "Nombre no encontrado")

    return render_template('index.html', nombre_ingles=nombre_ingles)

if __name__ == '__main__':
    app.run(debug=True)